flowchart TD
	Input[/req: MapMatchingReq/]
  Output["
    (output)
    movementIdOrdMapping
  "]

  subgraph CreateGpsRecord
    direction TB

    subgraph req.data.forEach
    direction LR
    subgraph Eligibility
      direction LR
      E1{"
        ord == 0 or the distance 
        from the last eligible 
        GpsRecord over 30m?
      "} 
			ET[gpsRecord.eligible == true]
			EF[gpsRecord.eligible == false]

			E1 --Yes--> ET
			E1 --No--> EF
    end
    
    subgraph Assignment
      direction TB
      Ord[/"
        movementId = data.movementId

        gpsRecord.ord=movement.ord++
      "/]
      Add["
        movement.gpsRecordList.add(gpsRecord)
        movementIdOrdMapping[movementId]
        .add(gpsRecord.ord)
      "]

      Ord --> Add

    end

    Eligibility --> Assignment

  end
  end

  subgraph Variables
    Movement["
      movement: Movement(id, ord, gpsRecordList, count,
      roadLink, roadNode, emissionList, transitionList, routeList)
      
      movementIdOrdMapping: Map<String, List<Int>>
    "] 
  end

Input --> CreateGpsRecord --> Output
