flowchart LR

	I[/req: movementIdOrdMapping/]
	GpsRecordListForEach["
		req.forEach
		(movement, ordList) ->
	"]
	subgraph UpdateRoadNetwork
		direction TB

		UpdateOrdList["
			lastEligibleGpsRecord = movement.gpsRecord
			.maxOf{ord < min(ordList)}
			?: 0

			ordList
			.add(lastEligibleGpsRecord.ord)

		"]

		GetLatestEligibleGpsRecord["
			make buffer(r=0.003) with gpsRecord list:
			ordList.map{ it -> latest gpsRecord where ord <= it and eligible }
		"]

		GetRoadLink["
			get roadLinks which intersect with buffer
			get roadNodes which intersect with buffer
		"]


	GpsRecordListForEach --> UpdateOrdList --> GetLatestEligibleGpsRecord --> GetRoadLink
	end

I --> UpdateRoadNetwork