flowchart TB

	I[/req: movementIdOrdMapping/]
	subgraph UpdateRoadNetwork

		subgraph req.forEach 
			it[/"(movement, ordList) ->"/]

			UpdateOrdList[/"
				lastEligibleGpsRecord = movement.gpsRecordList
				.maxOf{ord < min(ordList)}
				?: movement.GpsRecordList[0]
			"/]

			GetLatestEligibleGpsRecord["
				make buffer(r = 0.003) polygon with gpsRecord list with: 
				ordList.map { it -> latest gpsRecord.first{ ord <= it and eligible } }
			"]

			GetRoadLink[/"
				intersectsRoadLinks = get roadLinks from DB which intersect with buffer
				intersectsRoadNodes = get roadNodes from DB which intersect with buffer
			"/]

			AddRoadLink["
				movement.roadLink.addAll(intersectsRoadLinks)
				movement.roadNode.addAll(intersectsRoadNodes)
			"]

			it --> UpdateOrdList --> GetLatestEligibleGpsRecord --> GetRoadLink --> AddRoadLink

		end
		
	end

	Termination("Termination UpdateRoadNetwork")

I --> UpdateRoadNetwork --> Termination