flowchart LR
    Input[/req: movementIdOrdMapping/]

    subgraph Emission

        ReqForEach["
            req.forEach
            (movement, ordList) ->

            lastEligibleGpsRecord = movement.gpsRecord
			.maxOf{ord < min(ordList)}
        "]

        NodeCandidateListLoop["
            lastEligibleGpsRecord.NodeCandidateList.forEach
            nodeCandidate ->
        "]

        GetEmission["
            1. Get distance between nodeCandidate and lastEligibleGpsRecord 
            2. Calculate emission probability of NodeCandidate
        "]

        AddEmission["
            movement.emissionList.add(Emission)
        "]
        
        ReqForEach --> NodeCandidateListLoop --> GetEmission --> AddEmission
    end
    Input --> Emission