flowchart TB
    Input[/req: movementIdOrdMapping/]

    subgraph UpdateEmission

        subgraph req.forEach
            direction TB 
            
            itReq[/"(movement, ordList) ->"/]

            subgraph ordList.forEach
                direction TB
                itOrdList[/"ord ->"/]
                lastEligibleGpsRecord[/"gpsRecord = movement.gpsRecordList(ord)"/]

            subgraph gpsRecord.NodeCandidateList.forEach
                direction TB
                itNodeCandidate[/"nodeCandidate ->"/]

                GetEmission["
                    1. Get distance between nodeCandidate and gpsRecord 
                    2. Calculate emission probability of NodeCandidate
                    3. Create Emission object
                "]

                AddEmission["
                    movement.emissionList.add(Emission)
                "]

                itNodeCandidate --> GetEmission --> AddEmission
            end

            itOrdList --> lastEligibleGpsRecord --> gpsRecord.NodeCandidateList.forEach
            end

            itReq --> ordList.forEach

        end
    end
    
    Termination("Termination UpdateEmission")
    Input --> UpdateEmission --> Termination