flowchart LR
    Input[/req: movementIdOrdMapping/]
    subgraph Route
        GpsRecordListForEach["
            req.forEach1
            (movement, ordList) ->
	    "]

        OrdListForLoop["
            for (i=0 until ordList.lastIndex):
            start = movement.gpsRecordList[i]
            end = movement.gpsRecordList[i+1]
        "]

        GetPrevAndCurRouteList["
            curEmissionList = movement.emissionList where ord == i+1
            prevRouteList = movement.routeList where ord == i
        "]

        EmissionListForEach["
            curEmissionList.forEach
            emission -> 
        "]

        GetMaxProbRoute["
            transitionList = movement.transitionList where
            ord == i+1 && endNodeId == emission.nodeId

            getMaxProbRoute from transitionList where 
            (prevRoute = prevRouteList.lastNodeId == transition.startNodeId &&
            routeProb = prevRoute.prob * transition.prob * emission.prob)
            with maxRouteProb
            
        "]

        AddRoute["
            movement.routeList.add(route)
        "]



        GpsRecordListForEach --> OrdListForLoop --> GetPrevAndCurRouteList 
        GetPrevAndCurRouteList --> EmissionListForEach --> GetMaxProbRoute
        GetMaxProbRoute --> AddRoute
    end

Input --> Route